name: App update

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build of docker image
        run : |
          docker build -t terezabisharyan/simple-nodejs:${GITHUB_SHA::7} ./app/

      - name: Push image to DockerHub
        run : |
          docker login -u terezabisharyan -p ${{ secrets.DOCKER_HUB_PSW}}
          docker push terezabisharyan/simple-nodejs:${GITHUB_SHA::7}

  Change-image-tag-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'Tereza'
          git config --global user.email 'an3146073@gmail.com'

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.PRIV_KEY }}
          private-key-name: github
          
      - name: Clone target repository
        run: git clone git@github.com:tereza-arta/deploy-node-app.git

      - name: Set Short Git SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update YAML file with yq
        working-directory: deploy-node-app
        run: |
          yq '.spec.template.spec.containers.[0].image = "terezabisharyan/simple-nodejs:${{env.SHORT_SHA}}"' -i example-app/deploy.yml

      - name: Commit and Push Changes
        working-directory: deploy-node-app
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKER_HUB_PSW }}
        run: |
          git add example-app/deploy.yml
          git commit -m "Update image in k8s deployment"
          git push origin main       
    
